"""Pre-build script: gzip web assets and generate C++ PROGMEM header.

Reads data_embed/index.html, style.css, script.js, gzip-compresses each
at level 9, and generates include/web_assets.h with const uint8_t PROGMEM
arrays and length constants. This embeds the web UI into firmware flash
without needing SPIFFS or linker objcopy tricks.
"""
import gzip
import os

Import("env")

files = [
    ('data_embed/index.html', 'text/html',     'INDEX_HTML'),
    ('data_embed/style.css',  'text/css',      'STYLE_CSS'),
    ('data_embed/script.js',  'text/javascript','SCRIPT_JS'),
]

header_path = 'include/web_assets.h'

def to_c_array(data, var_name):
    lines = []
    lines.append('const uint8_t %s[] PROGMEM = {' % var_name)
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        hex_vals = ','.join('0x%02x' % b for b in chunk)
        lines.append('  ' + hex_vals + ',')
    # Remove trailing comma on last line
    if lines[-1].endswith(','):
        lines[-1] = lines[-1][:-1]
    lines.append('};')
    lines.append('const size_t %s_LEN = %d;' % (var_name, len(data)))
    return '\n'.join(lines)

chunks = []
for src_path, mime, var_name in files:
    with open(src_path, 'rb') as f:
        raw = f.read()
    compressed = gzip.compress(raw, compresslevel=9)
    ratio = (1 - len(compressed) / len(raw)) * 100 if len(raw) > 0 else 0
    print('compress.py: %s  %d -> %d bytes (%.0f%% saved)' %
          (src_path, len(raw), len(compressed), ratio))
    chunks.append((var_name, compressed))

with open(header_path, 'w') as f:
    f.write('// AUTO-GENERATED by tools/compress.py — do not edit.\n')
    f.write('#pragma once\n')
    f.write('#include <Arduino.h>\n\n')
    for var_name, data in chunks:
        f.write(to_c_array(data, var_name))
        f.write('\n\n')

print('compress.py: wrote %s' % header_path)
