#include "web_admin.h"

#include <WiFi.h>
#include <ESPAsyncWebServer.h>
#include <DNSServer.h>

#include "beacon_config.h"
#include "web_assets.h"  // generated by tools/compress.py

// External references to main.cpp globals and functions.
extern BeaconConfig config;
extern void saveConfig();
extern void loadDefaultConfig();
extern bool forceTransmit;
extern void testPttOnly();
extern float readBatteryVoltage();
extern uint8_t readBatteryPercent();
extern uint8_t foxNumberFromId(const String &id);
extern uint32_t resolvedStartupDelaySeconds();
extern int beaconStateValue();

static AsyncWebServer server(80);
static DNSServer dnsServer;
static bool running = false;
static String apSsid;
static String apIp = "10.0.0.8";

static uint32_t lastActivityMs = 0;

static String stateName(int s) {
  switch (s) {
    case 0: return "StartupDelay";
    case 1: return "Idle";
    case 2: return "Transmitting";
    case 3: return "ContinuousTransmit";
    case 4: return "LowBatteryHalt";
    default: return "Unknown";
  }
}

static void markActivity() {
  lastActivityMs = millis();
}

// --- Async request handlers ---

static void handleRoot(AsyncWebServerRequest *request) {
  markActivity();
  AsyncWebServerResponse *response = request->beginResponse(
      200, "text/html", INDEX_HTML, INDEX_HTML_LEN);
  response->addHeader("Content-Encoding", "gzip");
  response->addHeader("Cache-Control", "no-store");
  request->send(response);
}

static void handleStyle(AsyncWebServerRequest *request) {
  markActivity();
  AsyncWebServerResponse *response = request->beginResponse(
      200, "text/css", STYLE_CSS, STYLE_CSS_LEN);
  response->addHeader("Content-Encoding", "gzip");
  response->addHeader("Cache-Control", "max-age=3600");
  request->send(response);
}

static void handleScript(AsyncWebServerRequest *request) {
  markActivity();
  AsyncWebServerResponse *response = request->beginResponse(
      200, "text/javascript", SCRIPT_JS, SCRIPT_JS_LEN);
  response->addHeader("Content-Encoding", "gzip");
  response->addHeader("Cache-Control", "max-age=3600");
  request->send(response);
}

static void handleGetConfig(AsyncWebServerRequest *request) {
  markActivity();
  String json = "{";
  json += "\"call\":\"" + config.callSign + "\",";
  json += "\"fox\":\"" + config.foxId + "\",";
  json += "\"beaconMode\":" + String(config.beaconMode ? "true" : "false") + ",";
  json += "\"foxSync\":" + String(config.foxSyncEnabled ? "true" : "false") + ",";
  json += "\"foxNum\":" + String(foxNumberFromId(config.foxId)) + ",";
  json += "\"startup\":" + String(config.startupDelaySeconds) + ",";
  json += "\"startupResolved\":" + String(resolvedStartupDelaySeconds()) + ",";
  json += "\"tx\":" + String(config.transmitSeconds) + ",";
  json += "\"idle\":" + String(config.idleSeconds) + ",";
  json += "\"beaconId\":" + String(config.beaconIdIntervalSeconds) + ",";
  json += "\"wpm\":" + String(config.cwWpm) + ",";
  json += "\"tone\":" + String(config.cwToneHz) + ",";
  json += "\"warble\":" + String(config.warbleEnabled ? "true" : "false") + ",";
  json += "\"warbleLow\":" + String(config.warbleLowHz) + ",";
  json += "\"warbleHigh\":" + String(config.warbleHighHz) + ",";
  json += "\"warbleStep\":" + String(config.warbleStepMs) + ",";
  json += "\"pttActiveLow\":" + String(config.pttActiveLow ? "true" : "false") + ",";
  json += "\"lead\":" + String(config.pttLeadMs) + ",";
  json += "\"tail\":" + String(config.pttTailMs) + ",";
  json += "\"batteryEnabled\":" + String(config.batteryEnabled ? "true" : "false") + ",";
  json += "\"batteryScale\":" + String(config.batteryScale, 3) + ",";
  json += "\"lowBattery\":" + String(config.lowBatteryVoltage, 2) + ",";
  json += "\"wifiAp\":" + String(config.wifiApEnabled ? "true" : "false") + ",";
  json += "\"wifiApTimeout\":" + String(config.wifiApTimeoutMinutes) + ",";
  json += "\"ecoMode\":" + String(config.displayEcoMode ? "true" : "false") + ",";
  json += "\"state\":\"" + stateName(beaconStateValue()) + "\",";
  if (config.batteryEnabled) {
    json += "\"battery\":\"" + String(readBatteryVoltage(), 2) + "\",";
    json += "\"batteryPct\":" + String(readBatteryPercent()) + ",";
  } else {
    json += "\"battery\":\"N/A\",";
  }
  json += "\"apSsid\":\"" + apSsid + "\",";
  json += "\"ip\":\"" + apIp + "\"";
  json += "}";
  request->send(200, "application/json", json);
}

static void handlePostConfig(AsyncWebServerRequest *request) {
  markActivity();
  if (!request->hasParam("call", true)) {
    request->send(400, "text/plain", "Missing form data");
    return;
  }

  auto param = [&](const String &name) -> String {
    if (request->hasParam(name, true))
      return request->getParam(name, true)->value();
    return "";
  };

  config.callSign = param("call");
  config.foxId = param("fox");

  String mode = param("mode");
  config.beaconMode = (mode == "beacon" || mode == "continuous");

  String foxSync = param("fox_sync");
  config.foxSyncEnabled = (foxSync == "on" || foxSync == "true" || foxSync == "1");

  config.startupDelaySeconds = constrain(param("startup").toInt(), 0UL, 3600UL);
  config.transmitSeconds = constrain(param("tx").toInt(), 3UL, 600UL);
  config.idleSeconds = constrain(param("idle").toInt(), 5UL, 3600UL);
  config.beaconIdIntervalSeconds = constrain(param("beacon_id").toInt(), 10, 600);

  config.cwWpm = constrain(param("wpm").toInt(), 5, 35);
  config.cwToneHz = constrain(param("tone").toInt(), 300, 1800);

  String warble = param("warble");
  config.warbleEnabled = (warble == "on" || warble == "true" || warble == "1");
  config.warbleLowHz = constrain(param("warble_low").toInt(), 300, 1800);
  config.warbleHighHz = constrain(param("warble_high").toInt(), 300, 1800);
  config.warbleStepMs = constrain(param("warble_step").toInt(), 100, 3000);

  String ptt = param("ptt");
  config.pttActiveLow = (ptt == "active_low");
  config.pttLeadMs = constrain(param("lead").toInt(), 50, 3000);
  config.pttTailMs = constrain(param("tail").toInt(), 50, 3000);

  String battery = param("battery");
  config.batteryEnabled = (battery == "on" || battery == "true" || battery == "1");
  config.batteryScale = constrain(param("battery_scale").toFloat(), 1.0f, 10.0f);
  config.lowBatteryVoltage = constrain(param("low_battery").toFloat(), 2.5f, 15.0f);

  String wifiAp = param("wifi_ap");
  config.wifiApEnabled = (wifiAp == "on" || wifiAp == "true" || wifiAp == "1");
  config.wifiApTimeoutMinutes = constrain(param("wifi_ap_timeout").toInt(), 0, 1440);

  String ecoMode = param("eco_mode");
  config.displayEcoMode = (ecoMode == "on" || ecoMode == "true" || ecoMode == "1");

  saveConfig();
  request->send(200, "text/plain", "Saved. Settings will apply on next cycle or reboot.");
}

static void handleTest(AsyncWebServerRequest *request) {
  markActivity();
  forceTransmit = true;
  request->send(200, "text/plain", "Test transmission queued.");
}

static void handlePttTest(AsyncWebServerRequest *request) {
  markActivity();
  testPttOnly();
  request->send(200, "text/plain", "PTT test completed.");
}

static void handleDefaults(AsyncWebServerRequest *request) {
  markActivity();
  loadDefaultConfig();
  saveConfig();
  request->send(200, "text/plain", "Defaults restored and saved. Reboot recommended.");
}

static void handleReboot(AsyncWebServerRequest *request) {
  markActivity();
  request->send(200, "text/plain", "Rebooting...");
  delay(200);
  ESP.restart();
}

static void handleNotFound(AsyncWebServerRequest *request) {
  markActivity();
  // Captive portal: redirect all unknown URLs to root.
  request->redirect("http://10.0.0.8/");
}

// --- Public API ---

void webAdminInit(const char *apNamePrefix) {
  uint64_t mac = ESP.getEfuseMac();
  char macSuffix[5];
  snprintf(macSuffix, sizeof(macSuffix), "%02X%02X",
           (uint8_t)(mac >> 8), (uint8_t)mac);
  apSsid = String(apNamePrefix) + "-" + macSuffix;

  WiFi.mode(WIFI_AP);
  WiFi.softAPConfig(IPAddress(10, 0, 0, 8), IPAddress(10, 0, 0, 8), IPAddress(255, 255, 255, 0));
  WiFi.softAP(apSsid.c_str());
  apIp = WiFi.softAPIP().toString();

  // Captive portal DNS: redirect all queries to our IP.
  dnsServer.start(53, "*", WiFi.softAPIP());

  server.on("/", HTTP_GET, handleRoot);
  server.on("/style.css", HTTP_GET, handleStyle);
  server.on("/script.js", HTTP_GET, handleScript);
  server.on("/api/config", HTTP_GET, handleGetConfig);
  server.on("/api/config", HTTP_POST, handlePostConfig);
  server.on("/api/test", HTTP_POST, handleTest);
  server.on("/api/ptt_test", HTTP_POST, handlePttTest);
  server.on("/api/defaults", HTTP_POST, handleDefaults);
  server.on("/api/reboot", HTTP_POST, handleReboot);
  server.onNotFound(handleNotFound);
  server.begin();

  running = true;
  lastActivityMs = millis();
  Serial.printf("9M2PJU Fox Hunt Beacon — Web admin AP: %s, IP: %s\n", apSsid.c_str(), apIp.c_str());
}

void webAdminLoop() {
  if (!running) return;

  // Process captive portal DNS requests.
  dnsServer.processNextRequest();

  // Track station connections as activity.
  if (WiFi.softAPgetStationNum() > 0) {
    markActivity();
  }

  // Auto-off AP after timeout with no activity.
  if (config.wifiApTimeoutMinutes > 0) {
    uint32_t timeoutMs = (uint32_t)config.wifiApTimeoutMinutes * 60UL * 1000UL;
    if (millis() - lastActivityMs >= timeoutMs) {
      Serial.printf("WiFi AP auto-off after %u minutes of inactivity.\n",
                    config.wifiApTimeoutMinutes);
      config.wifiApEnabled = false;
      webAdminStop();
    }
  }
}

void webAdminStop() {
  if (!running) return;
  server.end();
  dnsServer.stop();
  WiFi.softAPdisconnect(true);
  WiFi.mode(WIFI_OFF);
  running = false;
  Serial.println(F("Web admin AP stopped."));
}

String webAdminGetIp() {
  return apIp;
}

String webAdminGetSsid() {
  return apSsid;
}

bool webAdminIsRunning() {
  return running;
}
